routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandlordController;
use App\Http\Controllers\LocataireController;

use App\Http\Controllers\ImmeubleController;
use App\Http\Controllers\LocationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('dashboard', [CustomAuthController::class, 'dashboard'])->name('dashboard')->middleware('auth'); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/show/{id}',[HomeController::class,'show'])->name('home.show');
// Route::get('/a', function () {
//     return view('layoutsHome.app');
// });



Route::resource('landlord', LandlordController::class);
Route::resource('locataires', LocataireController::class);

Route::resource('locations', LocationController::class);

Route::resource('immeubles', ImmeubleController::class);

app/Models/Location.php
<?php

namespace App\Models;

use App\Models\Immeuble;
use App\Models\Locataire;
// use App\Http\Controllers\ImmeubleController;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Location extends Model
{
    use  HasFactory,  Searchable;

 
        protected $fillable = ['immeuble_id','locataire_id','type_location', 'debut_bail','fin_bail','moyen_payement','payement'];
   
   public function immeuble(){
    return $this->belongsTo(Immeuble::class);
   }
   public function locataire(){
    return $this->belongsTo(Locataire::class);
   }
   public function toSearchableArray()
   {
       return [
           
           'payement' => $this->payement,

           
       ];
   }
}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Immeuble;
use App\Models\Location;
use App\Models\Locataire;
use Illuminate\Http\Request;

class LocationController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)

    { if($request->filled('search')){
        $locations = location::search($request->search)->simplePaginate(3);
        if ($locations->isEmpty()) {
            $message = 'Aucun résultat trouvé pour locations.';
            return view('location.index', compact('locations', 'message'));
        }
    }else{
        $locations = Location::simplePaginate(3);
    }
      
      return view('location.index' ,compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    { 
        $immeubles = Immeuble::all();
        $locataires = Locataire::all();
        return view('location.create',compact('immeubles','locataires'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
       $request->validate([
        'type_location' => 'required',
        'immeuble_id' => 'required',
        'locataire_id' => 'required',
        'debut_bail' => 'required',
        'fin_bail' => 'required|date|after:debut_bail',
        'moyen_payement' => 'required',
        'payement'=>'required',
       ]);
       Location::create($request->only(['immeuble_id','locataire_id','type_location','debut_bail','fin_bail','moyen_payement','payement']));
       return back();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Location $location)
    {
        $immeubles = Immeuble::all();
        $locataires = Locataire::all();


        return view('location.edit',compact('immeubles','locataires','location'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Location $location)
    {
        $request->validate([
            'type_location' => 'required',
        'immeuble_id' => 'required',
        'locataire_id' => 'required',
            'debut_bail' => 'required',
            'fin_bail' => 'required|date|after:debut_bail',
            'moyen_payement' => 'required',
            'payement'=>'required',
           ]);
        
        $location->fill($request->post())->save();

        return back();
    }
    /**
     * Remove the specified resource from storage.
     */
    // public function destroy(Location $location)
    // {
        
    //     $location->delete();
    //     return back();
    
    // }
    
    public function destroy(Location $location){
        $location->delete();
        $notification = [
            'message' => 'Location Deleted Sucessfully.!',
            'alert-type' => 'info'
        ];
        return back()->with($notification);
    }
}

resources/views/location/create.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 location
@endsection

@section('title_page2')
@endsection

@section('content')

<div class="card mb-4">
   @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 
  <div class="card-header">
  Creer nouveau location
  </div>
  <div class="card-body">
  <form method="POST" action="{{ route('locations.store') }}" enctype="multipart/form-data">
      @csrf

      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label for="immeuble" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Immeuble</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="immeuble_id"  name="immeuble_id">
                  <option value="">Selecte type d'immeuble</option>

                    @foreach($immeubles as $immeuble)
                    <option value="{{$immeuble->id}}">{{$immeuble->type}}</option>
                    @endforeach
                </select>
     </div>
   </div>
   <div class="col">
          <div class="mb-3 row">
          <label for="type_location" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de location</label> <br>
              <select class="col-lg-10 col-md-6 col-sm-12" id="type_location"  name="type_location">
              <option value="">Selecte type  de location</option>

                <option value="habitationvide">Bail d'habitation vide</option>
                <option value="habitationmeble">Bail d'habitation meublé</option>
                <option value="etudiant">Bail meublé etudiant</option>
                <option value="parkig">Bail parking/garage</option>
                <option value="mixte">Bail mixte</option>
                <option value="commercial">Bail commercial</option>
                <option value="autre">Autre</option>
              </select>
  </div>
    </div>
    </div>

<div class="row">

<div class="col">
          <div class="mb-3 row">
            <label for="locataire" class="col-lg-2 col-md-6 col-sm-12 col-form-label">locataire</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="locataire_id"  name="locataire_id">
              <option value="">Selecte type  de locataire</option>

                    @foreach($locataires as $locataire)

                    <option value="{{$locataire->id}}">{{$locataire->type_locataire}}</option>
                    @endforeach
                </select>
     </div>
   </div>
 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Debut du bail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="debut_bail" value="{{ old('debut_bail') }}" type="date" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Fin  du bail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="fin_bail" value="{{ old('fin_bail') }}" type="date" class="form-control">
            </div>
          </div>
        </div>
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Moyen de payement</label>
            <div class="col-lg-10 col-md-6 col-sm-12">

              <select class="col-lg-10 col-md-6 col-sm-12" id="moyen_payement"  name="moyen_payement">
              <option value="">Selecte Moyen de payement</option>

                    <option value="carte">Carte de crédit</option>
                    <option value="cheque"> Chéque</option>
                    <option value="especes"> Espéces</option>
                    <option value="virement"> Virement</option>

                </select>
            </div>
          </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Payement</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
        
                <select class="col-lg-10 col-md-6 col-sm-12" id="payement"  name="payement">
              <option value="">Selecte Payement</option>
                    <option value="mensuel">Mensuel</option>
                    <option value="bimestriel">Bimestriel</option>
                    <option value="trimestriel">Trimestriel</option>
                    <option value="quadrimestriel">Quadrimestriel</option>
                    <option value="semestriel">Semestriel</option>
                    <option value="annuel">Annuel</option>
                    <option value="forfaitaire">Forfaitaire</option>
                </select>
              </div>
            </div>
          </div> 

        </div> 
        <a class="btn btn-primary" href="{{ route('locations.index') }}"> Retour</a>
  
        <button type="submit" class="btn btn-primary">Ajouter</button>
</div>
</div>
@endsection

resources/views/location/edit.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 location
@endsection

@section('title_page2')
@endsection

@section('content')

<div class="card mb-4">
   @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 
  <div class="card-header">
  Edit  location
  </div>
  <div class="card-body">
  <form method="POST" action="{{ route('locations.update',$location->id) }}" enctype="multipart/form-data">
      @csrf 
@method('PUT')

      <div class="row">
        <div class="col">
          <div class="mb-3 row">
          <label for="immeuble" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Immeuble</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="immeuble_id"  name="immeuble_id">
                    @foreach($immeubles as $immeuble)
                    <option value="{{$immeuble->id}} ">{{$immeuble->type}}</option>
                    @endforeach
                </select>
     </div>
   </div>
   <div class="col">
          <div class="mb-3 row">
          <label for="type_location" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de location</label> <br>
              <select class="col-lg-10 col-md-6 col-sm-12" id="type_location"  value='{{$location->type_location}}' name="type_location">
                <option value="habitationvide"   {{$location->type_location == 'habitationvide' ? 'selected' : '' }}>Bail d'habitation vide</option>
                <option value="habitationmeble"  {{$location->type_location == 'habitationmeble' ? 'selected' : '' }}>Bail d'habitation meublé</option>
                <option value="etudiant"  {{$location->type_location == 'etudiant' ? 'selected' : '' }}>Bail meublé etudiant</option>
                <option value="parkig"  {{$location->type_location == 'parkig' ? 'selected' : '' }}>Bail parking/garage</option>
                <option value="mixte"  {{$location->type_location == 'mixte' ? 'selected' : '' }}>Bail mixte</option>
                <option value="commercial"  {{$location->type_location == 'commercial' ? 'selected' : '' }}>Bail commercial</option>
                <option value="autre"  {{$location->type_location == 'autre' ? 'selected' : '' }}>Autre</option>
              </select>
  </div>
    </div>
    </div>

<div class="row">

    
<div class="col">
          <div class="mb-3 row">
            <label for="locataire" class="col-lg-2 col-md-6 col-sm-12 col-form-label">locataire</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="locataire_id"  name="locataire_id">
                    @foreach($locataires as $locataire)
                    <option value="{{$locataire->id}}">{{$locataire->type_locataire}}</option>
                    @endforeach
                </select>
     </div>
   </div>
 
 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Debut du bail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="debut_bail" value='{{$location->debut_bail}}' type="date" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Fin  du bail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="fin_bail" value='{{$location->fin_bail}}' type="date" class="form-control">
            </div>
          </div>
        </div>
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Moyen de payement</label>
            <div class="col-lg-10 col-md-6 col-sm-12">

              <select class="col-lg-10 col-md-6 col-sm-12" value='{{$location->moyen_payement}}' id="moyen_payement"  name="moyen_payement">
                    <option value="bureaux" {{$location->moyen_payement == 'bureaux' ? 'selected' : '' }}>Bureaux</option>
                    <option value="carte" {{$location->moyen_payement == 'carte' ? 'selected' : '' }} >Carte de crédit</option>
                    <option value="cheque" {{$location->moyen_payement == 'cheque' ? 'selected' : '' }}> Chéque</option>
                    <option value="especes" {{$location->moyen_payement == 'especes' ? 'selected' : '' }}> Espéces</option>
                    <option value="virement" {{$location->moyen_payement == 'virement' ? 'selected' : '' }}> Virement</option>

                </select>
            </div>
          </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Payement</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
        
                <select class="col-lg-10 col-md-6 col-sm-12" id="payement"  value='{{$location->payement}}' name="payement">
                    <option value="mensuel"  {{$location->payement == 'mensuel' ? 'selected' : '' }} >Mensuel</option>
                    <option value="bimestriel" {{$location->payement == 'bimestriel' ? 'selected' : '' }} >Bimestriel</option>
                    <option value="trimestriel" {{$location->payement == 'trimestriel' ? 'selected' : '' }} >Trimestriel</option>
                    <option value="quadrimestriel" {{$location->payement == 'quadrimestriel' ? 'selected' : '' }} >Quadrimestriel</option>
                    <option value="semestriel" {{$location->payement == 'semestriel' ? 'selected' : '' }} >Semestriel</option>
                    <option value="annuel" {{$location->payement == 'annuel' ? 'selected' : '' }} >Annuel</option>
                    <option value="forfaitaire" {{$location->payement == 'forfaitaire' ? 'selected' : '' }} >Forfaitaire</option>
                </select>
              </div>
            </div>
          </div> 

        </div> 
        <a class="btn btn-primary" href="{{ route('locations.index') }}"> Retour</a>
  
        <button type="submit" class="btn btn-primary">Ajouter</button>
</div>
</div>
@endsection

resources/views/location/index.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
Location
@endsection

@section('title_page2')

@endsection
@section('content')
<div class="row">

</div>
<div class="dropdown-divider border-black"></div>
<div class="row ml-4 ">
    <div class="col-md-6">
        <h5 class="fw-bold mb-0">liste des Locations</h5>
    </div>
    <div class="col-md-6">
        <!-- <div class="d-flex justify-content-end">
                <a href="/process.php?action=export" class="btn btn-success btn-sm" id="export"><i class="fas fa-table"></i> Exporter</a>
            </div> -->
    </div>
</div>
<div class="dropdown-divider border-black"></div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="button">
                        <a href="{{ route('locations.create') }}" class="btn btn-sm btn-primary">nouveau location</a>
                    </div>
                    <br>
                    <form method="GET">
                        <div class="input-group mb-3">
                            <input type="text" name="search" value="" class="form-control" placeholder="recherche par payement..." aria-label="Search" aria-describedby="button-addon2">
                            <button class="btn btn-success" type="submit" id="button-addon2">Recherche</button>
                        </div>
                    </form>
                    <table class="table table-responsive-sm table-bordered table-striped">
                        <thead>
                            <th scope="col">Locataire</th>

                            <th scope="col">Immeuble</th>

                            <th scope="col">Debut du bail</th>
                            <th scope="col">Fin du bail</th>
                            <th scope="col">Paiment</th>

                            <th scope="col ">Action</th>
                        </thead>
                        <tbody>
                            @foreach ($locations as $location)

                            <tr>
                                <td>{{ $location->Locataire->type_locataire }}</td>
                                <td> {{$location->Immeuble->type}} </td>
                                <td>{{ $location->debut_bail }}</td>
                                <td>{{ $location->fin_bail}}</td>
                                <td>{{ $location->payement }}</td>
                                <td class="text-center">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a class="btn btn-success" href="{{ route('locations.edit',$location->id) }}">modifier</a>
                                        </div>
                                        <div class="col-md-6">

                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $location->id }}">Supprimer</button>
                                        </div>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="deleteModal{{ $location->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <center>
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h3 class="modal-title">Supprimer la confirmation de location</h3><br>
                                                </div>
                                            </center>
                                                <div class="modal-body">
                                                    <p>Êtes-vous sûr de vouloir supprimer cet location?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-hover btn-primary" data-dismiss="modal">Annuler</button>
                                                    <form action="{{ route('locations.destroy', ['location' => $location->id]) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Supprimer</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @if (isset($message))
    <div class="alert alert-info">{{ $message }}</div>
@endif
        
                </div>
                <div class="card-body d-flex justify-content-left">
                    {!! $locations->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection