routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandlordController;
use App\Http\Controllers\LocataireController;

use App\Http\Controllers\ImmeubleController;
use App\Http\Controllers\LocationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('dashboard', [CustomAuthController::class, 'dashboard'])->name('dashboard')->middleware('auth'); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/show/{id}',[HomeController::class,'show'])->name('home.show');
// Route::get('/a', function () {
//     return view('layoutsHome.app');
// });



Route::resource('landlord', LandlordController::class);
Route::resource('locataires', LocataireController::class);

Route::resource('locations', LocationController::class);

Route::resource('immeubles', ImmeubleController::class);

app/Models/Immeuble.php
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Immeuble extends Model
{
use  HasFactory,  Searchable;
    protected $fillable = ['type','type_location','addresse','telephone','images','ville','code','region','surface','etage','prix','description','nbr_chambre','info'];

    public function setInfoAttribute($value)
    {
        $this->attributes['info'] = json_encode($value);
    }

    public function getInfoAttribute($value)
    {
        return $this->attributes['info'] = json_decode($value);
    }
    
    public function toSearchableArray()
    {
        return [
            
            'ville' => $this->ville,
            'type' => $this->type

            
        ];
    }
    
    protected $casts = [
        'images' => 'array'
    ];
}

app/Http/Controllers/ImmeubleController.php
<?php

namespace App\Http\Controllers;
use App\Models\Immeuble;
use App\Models\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\Redirect;
use App\Models\Immeuble\toSearchableArray;

class ImmeubleController extends Controller
{
    
    //     public function index(Request $request)
    //     {
           
           
    //         if($request->filled('search')){
    //                     $immeubles = Immeuble::search($request->search)->simplePaginate(3);
    //                 }else{
    //                     $immeubles = Immeuble::simplePaginate(3);
    //                 }

    //     return view('Immeuble.index', compact('immeubles'));
        
    // }
    public function index(Request $request)
    {
        if ($request->filled('search')) {
            $immeubles = Immeuble::search($request->search)->simplePaginate(3);
    
            if ($immeubles->isEmpty()) {
                $message = 'Aucun résultat trouvé pour immeubles.';
                return view('Immeuble.index', compact('immeubles', 'message'));
            }
        } else {
            $immeubles = Immeuble::simplePaginate(3);
        }
    
        return view('Immeuble.index', compact('immeubles'));
    }
    
    public function create()
    {
        return view('Immeuble.create');
    }
    public function store(Request $request)
    {
       $data= $request->validate([
            'type'=> 'required',
            'type_location'=> 'required',
            'addresse'=> 'required',
            'telephone'=> 'required',
            'images' => 'required|array',
            'ville'=> 'required',
            'code'=> 'required',
            'region'=> 'required',
            'surface'=> 'required',
            'etage'=> 'required',
             'prix'=> 'required',
            'description'=> 'required',
            'nbr_chambre'=> 'required',
            'info'=> 'required',
            
        ]);
        $images = [];

        foreach (  $data['images'] as $image) {
            $fileName = uniqid() . '.' . $image->getClientOriginalExtension();
            $image_path =  $image->storeAs('public/images', $fileName);

            array_push($images, $fileName);
        }
        $data['images'] = $images;
        $data['info'] = $request->input('info');
        Immeuble::create($data);
    
        return back();

    }
    public function edit(Immeuble $immeuble)
    {
        return view('Immeuble.edit',compact('immeuble'));
    }

    public function update(Request $request, Immeuble $immeuble)
    {
        $data =  $request->validate([
            'type'=> 'required',
            'type_location'=> 'required',
            'addresse'=> 'required',
            'telephone'=> 'required',
            'images' => 'required|array',
            'ville'=> 'required',
            'code'=> 'required',
            'region'=> 'required',
            'surface'=> 'required',
            'etage'=> 'required',
             'prix'=> 'required',
            'description'=> 'required',
            'nbr_chambre'=> 'required',
            'info'=> 'required',
        ]);
        $images = [];

        foreach (  $data['images'] as $image) {
            $fileName = uniqid() . '.' . $image->getClientOriginalExtension();
            $image_path =  $image->storeAs('public/images', $fileName);

            array_push($images, $fileName);
        }
        $data['images'] = $images;
        $immeuble->update($data);
        return back();
    }
   
    public function destroy(Request $request, Immeuble $immeuble)
    {
        $location = Location::where("immeuble_id", $immeuble->id)->pluck('immeuble_id');
        if ($location->isEmpty()) {
            if ($immeuble) {
                $immeuble->delete();
                session()->flash('error',"l'appartement  supprimée avec succès !");
              
            }
        } else {
            session()->flash('error', "Impossible de supprimer   parce que l'appartement est déjà utilisé");
        }
        return back();
    }
}

resources/views/Immeuble/create.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 Immeuble
@endsection



@section('content')

<div class="card mb-4">
 @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 
  <div class="card-header">
  Creer nouveau Immeuble
  </div>
  <div class="card-body">
  <form method="POST" action="{{ route('immeubles.store') }}"enctype="multipart/form-data">
      @csrf

      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label for="type" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type d'immeuble</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="type"  name="type">
                  <option value="">Selecte type d'immeuble</option>
                    <option value="appartement">Appartement</option>
                    <option value="atelier">Atelier</option>
                    <option value="boutique">Boutique</option>
                    <option value="bureaux">Bureaux</option>
                    <option value="chambre">Chambre</option>
                    <option value="garage">Garage</option>
                    <option value="local">local professionnel</option>
                    <option value="studio">Studio</option>
                    <option value="maison">Maison</option>
                    <option value="autre">Autre</option>
                </select>
     </div>
   </div>
   <div class="col">
          <div class="mb-3 row">
          <label for="type_location" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de location</label> <br>
              <select class="col-lg-10 col-md-6 col-sm-12" id="type_location"  name="type_location">
              <option value="">Selecte type Location</option>
               
              <option value="meublée">Meublée</option>
                <option  value="vide">Vide</option>
              </select>
  </div>
    </div>
    </div>

<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Adresse</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="addresse" value="{{ old('addresse') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Telephone</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="telephone"  value=""  placeholder="Telephone " type="text" class="form-control">

            </div>
          </div>
        </div>


        </div> 
<div class="row">

        <div class="col">
          
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Image</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
            </div>
          </div>
        </div>
        </div>

<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Ville</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="ville" value="{{ old('ville') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Code postal</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="code" value="{{ old('code') }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Region</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="region" value="{{ old('region') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Surface m2</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="surface" value="{{ old('surface') }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Etage</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="etage" value="{{ old('etage') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Prix</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="prix" value="{{ old('prix') }}" type="number" class="form-control">
              </div>
            </div>
          </div> 

        </div> 


<div class="row">
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Description</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="description"  type="text" class="form-control">
              </div>
            </div>
          </div> 

        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Nombre de chambres</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="nbr_chambre"
               type="number" class="form-control">
            </div>
          </div>
        </div>

        </div>

        <div class="row">
        <div class="col">
          
        <div class="mb-3 row">
            <label class="checkbox-inline col-lg-2 col-md-6 col-sm-12 col-form-label" >Informations complémentaires</label>
            <input type="checkbox" value="Accès Internet" name="info[]">Accès Internet <br>
            <input type="checkbox" value="Balcon" name="info[]"> Balcon <br>
            <input type="checkbox" value="Chauffage collectif" name="info[]">Chauffage collectif <br>
            <input type="checkbox" value="Interphone"name="info[]">Interphone <br>
            <input type="checkbox" value="Système de sécurité" name="info[]"> Système de sécurité <br>

          </div>
    </div>
    </div>
       

       
    <a class="btn btn-primary" href="{{ route('immeubles.index') }}"> Retour</a>

        <button type="submit" class="btn btn-primary">Ajouter</button>
        
</form>

</div>


</div>



</div>
</div>












@endsection

resources/views/Immeuble/edit.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 Immeuble
@endsection



@section('content')

<div class="card mb-4">
 @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 
  <div class="card-header">
 Edit Immeuble
  </div>
  
  <div class="card-body">
  <form method="POST" action="{{ route('immeubles.update',$immeuble->id) }}"enctype="multipart/form-data">
      @csrf
   @method('PUT')
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label for="type" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type d'immeuble</label> <br>
                  <select class="col-lg-10 col-md-6 col-sm-12" id="type" value='{{$immeuble->type}}'name="type">
                    <option value="appartement"{{ $immeuble->type == 'appartement' ? 'selected' : '' }}>Appartement</option>
                    <option value="atelier" {{ $immeuble->type == 'atelier' ? 'selected' : '' }} >Atelier</option>
                    <option value="boutique" {{ $immeuble->type == 'boutique' ? 'selected' : '' }}>Boutique</option>
                    <option value="bureaux" {{ $immeuble->type == 'bureaux' ? 'selected' : '' }}>Bureaux</option>
                    <option value="chambre" {{ $immeuble->type == 'chambre' ? 'selected' : '' }}>Chambre</option>
                    <option value="garage" {{ $immeuble->type == 'garage' ? 'selected' : '' }}>Garage</option>
                    <option value="local" {{ $immeuble->type == 'loca' ? 'selected' : '' }}>local professionnel</option>
                    <option value="studio" {{ $immeuble->type == 'studio' ? 'selected' : '' }}>Studio</option>
                    <option value="maison" {{ $immeuble->type == 'maison' ? 'selected' : '' }}>Maison</option>
                    <option value="autre" {{ $immeuble->type == 'autr' ? 'selected' : '' }}>Autre</option>
                </select>
     </div>
   </div>
   <div class="col">
          <div class="mb-3 row">
          <label for="type_location" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de location</label> <br>
              <select class="col-lg-10 col-md-6 col-sm-12" id="type_location" value="{{ $immeuble->type_location}}"  name="type_location">
                <option value="meublée" {{ $immeuble->type_location == 'meublée' ? 'selected' : '' }}>Meublée</option>
                <option  value="vide"  {{ $immeuble->type_location == 'vide' ? 'selected' : '' }}>Vide</option>
              </select>
  </div>
    </div>
    </div>

<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Adresse</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="addresse" value="{{ $immeuble->addresse}}" type="text" class="form-control">
            </div>
          </div>
        </div>
       
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Telephone</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
            <input name="telephone"  value="{{ $immeuble->telephone}}"  placeholder="Telephone " type="text" class="form-control">

            </div>
          </div>
        </div>

        </div> 
        <div class="row">

        <div class="col">
          
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Image</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
              <input class="form-control" type="file" name="images[]" >
            </div>
          </div>
        </div>
        </div>


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Ville</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="ville" value="{{  $immeuble->ville }}" type="text" class="form-control">
            </div>
          </div>
        </div>
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Code postal</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="code" value="{{ $immeuble->code }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Region</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="region" value="{{ $immeuble->region }}" type="text" class="form-control">
            </div>
          </div>
        </div>
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Surface m2</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="surface" value="{{  $immeuble->surface }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        </div> 


<div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Etage</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="etage" value="{{  $immeuble->etage }}" type="text" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Prix</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="prix" value="{{ $immeuble->prix}}" type="number" class="form-control">
              </div>
            </div>
          </div> 

        </div> 


<div class="row">
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Description</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="description" value="{{  $immeuble->description }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Nombre de chambres</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="nbr_chambre" value="{{ $immeuble->nbr_chambre }}" type="number" class="form-control">
            </div>
          </div>
        </div>

        </div>

        <div class="row">
        <div class="col">
          
        <div class="mb-3 row">
            <label class="checkbox-inline col-lg-2 col-md-6 col-sm-12 col-form-label" >Informations complémentaires</label>
            <input type="checkbox"  value="Accès Internet" name="info[]">Accès Internet <br>
            <input type="checkbox" value="Balcon" name="info[]"> Balcon <br>
            <input type="checkbox" value="Chauffage collectif" name="info[]">Chauffage collectif <br>
            <input type="checkbox" value="Interphone"name="info[]">Interphone <br>
            <input type="checkbox" value="Système de sécurité" name="info[]"> Système de sécurité <br>

          </div>
    </div>
    </div>
       

                          
    
  
                 <a class="btn btn-primary" href="{{ route('immeubles.index') }}"> Retour</a>
        <button type="submit" class="btn btn-primary">Ajouter</button>
        
</form>

</div>


</div>



</div>
</div>












@endsection

resources/views/Immeuble/index.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
Locataires
@endsection


@section('content')
    <div class="row">
    @if (session()->has('error'))
        <div class="alert alert-danger  bg-danger " id="success-alert">
            <div class="d-flex align-items-center">
               
                <div class="ms-3">
                    <!-- <h6 class="mb-0 text-white">Error</h6> -->
                    <div class="text-white">{{ session()->get('error') }}</div>
                </div>
            </div>
          
        </div>
    @endif 
    </div>
    <div class="dropdown-divider border-black"></div>
    <div class="row ml-4 ">
        <div class="col-md-6">
            <h5 class="fw-bold mb-0">liste des Immeubles</h5>
        </div>
        
    </div>
    <div class="dropdown-divider border-black"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                    <div class="button">
                        <a href="{{ route('immeubles.create') }}" class="btn btn-sm btn-primary">nouveau Immeuble</a>
                        </div>
                        <br>
         <form method="GET">
        <div class="input-group mb-3">
          <input 
            type="text" 
            name="search" 
            value="" 
            class="form-control" 
            placeholder="recherche par ville  et type d'immeuble ..." 
            aria-label="Search" 
            aria-describedby="button-addon2">
          <button class="btn btn-success" type="submit" id="button-addon2">Recherche</button>
        </div>
    </form>
                       

                        <table class="table table-responsive-sm table-bordered table-striped">
                            <thead>
                                <th>Type d'immeuble</th>
                                <th>Type de location</th>
                                <th>Ville</th>

                                <th>Superficie m2</th>
                               
                                <th>prix</th>
                                <th>Action</th>
                            </thead>
                            <tbody>

                                @foreach ($immeubles as $immeuble)
                                <tr>
                        <td>{{ $immeuble->type}}</td>
                         <td>{{ $immeuble->type_location}}</td>
                        <td>{{ $immeuble->ville}}</td>
                        <!-- <td >
                                        @foreach($immeuble->images as $image)
                                        <img src="{{asset('/storage/images/'.$image)}}" alt="multiple image"
                                            class="w-20 h-20 border border-blue-600">
                                        @endforeach
                                    </td> -->
                        <td>{{ $immeuble->surface}}</td>
                      
                        <td>{{ $immeuble->prix}}</td>
                        <td class="text-center">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a class="btn btn-success" href="{{ route('immeubles.edit',$immeuble->id) }}">modifier</a>
                                        </div>
                                        <div class="col-md-6">

                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{$immeuble->id }}">Supprimer</button>
                                        </div>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="deleteModal{{ $immeuble->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <center>
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h3 class="modal-title">Supprimer la confirmation d'immeuble</h3><br>
                                                </div>
                                            </center>
                                                <div class="modal-body">
                                                    <p>Êtes-vous sûr de vouloir supprimer cet immeuble ?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-hover btn-primary" data-dismiss="modal">Annuler</button>
                                                    <form action="{{ route('immeubles.destroy',$immeuble->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Supprimer</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                      
                                       
                                    </div>

                                </td>
                        
                        
                    </tr>
                    @endforeach    
                  
                                

                           
                            </tbody>
                        </table>
                        @if (isset($message))
    <div class="alert alert-info">{{ $message }}</div>
@endif
                    </div>
                    <div class="card-body d-flex justify-content-left">
            {!! $immeubles->links() !!}
        </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

@endsection 