routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandlordController;
use App\Http\Controllers\LocataireController;

use App\Http\Controllers\ImmeubleController;
use App\Http\Controllers\LocationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('dashboard', [CustomAuthController::class, 'dashboard'])->name('dashboard')->middleware('auth'); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/show/{id}',[HomeController::class,'show'])->name('home.show');
// Route::get('/a', function () {
//     return view('layoutsHome.app');
// });



Route::resource('landlord', LandlordController::class);
Route::resource('locataires', LocataireController::class);

Route::resource('locations', LocationController::class);

Route::resource('immeubles', ImmeubleController::class);

app/Models/Landlord.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Landlord extends Model
{
    use HasFactory;
    protected $fillable = ['nom', 'email','ville','region','telephone','codePostal','civilite', 'address','societe'];
}

app/Http/Controllers/LandlordController.php
<?php

namespace App\Http\Controllers;
use App\Models\Landlord;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LandlordController extends Controller
{  
    public function index()
    {

        $landlord = Landlord::simplePaginate(3);
        $user = Auth::user();
        return view('landlord.index', compact('landlord','user'));
    }
    public function create()
    {
        return view('landlord.index');
    }
    public function store(Request $request)
    {
        $request->validate([
            'nom' => 'required',
            'email' => 'required',
            'ville'=> 'required',
            'region'=> 'required',
            'telephone'=> 'required',
            'codePostal'=> 'required',
            'civilite'=> 'required',
            'address' => 'required',
        ]);
     
        Landlord::create($request->all());

        return back();
    }
    public function edit(Landlord $landlord)
    {
        return view('landlord.edit',compact('landlord'));
    }
    public function update(Request $request,Landlord $landlord)
    {
        $request->validate([
            'nom' => 'required',
            'email' => 'required',
            'ville'=> 'required',
            'region'=> 'required',
            'telephone'=> 'required',
            'codePostal'=> 'required',
            'civilite'=> 'required',
            'address' => 'required',
        ]);
        
        $landlord->fill($request->post())->save();

        return back();
    }
    public function show(Landlord $landlord)
    {
        return view('landlord.show',compact('landlord'));
    }

}

resources/views/landlord/index.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
Landlord
@endsection



@section('content')
<div class="card mb-4">
  <div class="card-header">
  Informations personnelles
  </div>
  <div class="card-body">
  @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif
   
    <form method="POST" action="{{ route('landlord.store') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">  Nom</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="nom" value="{{ $user->name }}"  placeholder="Nom *" type="text" class="form-control">
            </div>
          </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Telephone</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="telephone"  value="{{ $user->telephone }}"  placeholder="Telephone *" type="text" class="form-control">
              </div>
            </div>
          </div> 
        </div>
        <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Email </label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="email" value="{{ $user->email }}" placeholder="Email *" type="email" class="form-control">
            </div>
          </div>
        </div>
    
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Adresse	</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input class="form-control" placeholder="Adresse *" type="text" name="address">
              
            </div>
           
          </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Ville</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" placeholder="Ville *" name="ville">
              </div>
           </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Code Postal	</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" placeholder="Code Postal *" name="codePostal">
              </div>
            </div>
          </div>
        
      </div> 
      <div class="row">
        <div class="col">
          <div class="mb-3 row">
            <label for="civilite" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Civilite
</label> <br>
      <select class="col-lg-10 col-md-6 col-sm-12" id="civilite"  name="civilite">
      <option  value="">Select civilite</option>
        <option value="mll
        ">Mll
        </option>
        <option  value="mlle">Mlle</option>
        <option value="mme">Mme</option>
    </select>
  </div>
</div>
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Region	</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" placeholder='Region ' name="region">
              </div>
            </div>
          </div>
</div>

<div class="row">
       
<div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Societe	</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" placeholder=' Nom Societe' name="societe">
              </div>
            </div>
          </div>
         <div class="col">
          &nbsp;
        </div> 
</div>

     
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>


     
    
  </div>
</div>
@endsection