routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandlordController;
use App\Http\Controllers\LocataireController;

use App\Http\Controllers\ImmeubleController;
use App\Http\Controllers\LocationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('dashboard', [CustomAuthController::class, 'dashboard'])->name('dashboard')->middleware('auth'); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('/',[HomeController::class,'index'])->name('home.index');
Route::get('/show/{id}',[HomeController::class,'show'])->name('home.show');
// Route::get('/a', function () {
//     return view('layoutsHome.app');
// });



Route::resource('landlord', LandlordController::class);
Route::resource('locataires', LocataireController::class);

Route::resource('locations', LocationController::class);

Route::resource('immeubles', ImmeubleController::class);

app/Models/Locataire.php
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Locataire extends Model
{
    use HasFactory,Searchable;
    protected $fillable = ['type_locataire', 'locataire_name', 'locataire_prenom', 'email', 'ville', 'code','region', 'civilite', 'adresse', 'date'];
   
    public function toSearchableArray()
    {
        return [
            
            'ville' => $this->ville,
       

            
        ];
    }
}

app/Http/Controllers/LocataireController.php
<?php

namespace App\Http\Controllers;

use App\Models\Location;
use App\Models\Locataire;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocataireController extends Controller
{
    
    public function index(Request $request)
{
    if ($request->filled('search')) {
        $locataires = Locataire::search($request->search)->simplePaginate(3);

        if ($locataires->isEmpty()) {
            $message = 'Aucun résultat trouvé pour cette ville.';
            return view('locataires.index', compact('locataires', 'message'));
        }
    } else {
        $locataires = Locataire::simplePaginate(3);
    }

    return view('locataires.index', compact('locataires'));
}


    public function create()
    {
        return view('locataires.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'type_locataire' => 'required',
            'locataire_name' => 'required',
            'locataire_prenom' => 'required',
            'email' => 'required',
            'ville' => 'required',
            'code'=>'required',
            'region' => 'required',
            'civilite' => 'required',
            'adresse' => 'required',
            'date' => 'required',
        ]);
        Locataire::create($request->all());
        return back();
    }
    public function edit(Locataire $locataire)
    {
        return view('locataires.edit',compact('locataire'));
    }


    public function update(Request $request, Locataire $locataire)
    {
        $request->validate([
            'type_locataire' => 'required',
            'locataire_name' => 'required',
            'locataire_prenom' => 'required',
            'email' => 'required',
            'ville' => 'required',
            'code'=>'required',
            'region' => 'required',
            'civilite' => 'required',
            'adresse' => 'required',
            'date' => 'required',
        ]);
        
        $locataire->fill($request->post())->save();

        return back();
    }
    public function destroy(Request $request,  Locataire $locataire)
    {
        $location = Location::where("locataire_id", $locataire->id)->pluck('locataire_id');
        if ($location->isEmpty()) {
            if ($locataire) {
                $locataire->delete();
                session()->flash('error',"locataire supprimée avec succès !");
              
            }
        } else {
            session()->flash('error', "Impossible de supprimer   parce que locataire est déjà utilisé");
        }
        return back();
    }





}

resources/views/locataires/create.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 locataire
@endsection



@section('content')
<div class="card mb-4">
  <div class="card-header">
  Creer  nouveau locataire
  </div>
  <div class="card-body">
   @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 

    <form method="POST" action="{{ route('locataires.store') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
      <div class="col">
          <div class="mb-3 row">
            <label for="state" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de locataire</label> <br>
            <select class="col-lg-10 col-md-6 col-sm-12"id="type"  name="type_locataire">
            <option value="">Selecte type locataire</option>
       
            <option value="locataire">locataire
        </option>

        <option value="particulier">Particulier</option>
        <option value="societe">Société/Autre</option>
    </select>
  </div>
</div>


        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Nom locataire</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="locataire_name" value="{{ old('locataire_name') }}" type="text" class="form-control">
            </div>
          </div>
        </div>
        
        
        </div>
        <div class="row">
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Prenom locataire</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="locataire_prenom" value="{{ old('locataire_prenom') }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">E-mail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="email" value="{{ old('email') }}" type="email" class="form-control">
            </div>
          </div>
        </div>
    
       
    </div>

    <div class="row">
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Ville</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" name="ville">
              </div>
           </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Code postal</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" name="code">
              </div>
           </div>
        </div>

      
         {{-- <div class="col">
          &nbsp;
        </div> --}}
      </div> 
      <div class="row">
    

      <div class="col">
   <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Region</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" name="region">
              </div>
            </div>
         </div>
<div class="col">
          <div class="mb-3 row">
            <label for="civilite" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Civilite
</label> 
<br>
      <select class="col-lg-10 col-md-6 col-sm-12" id="civilite"  name="civilite">
      <option value="">Selecte type civilite</option>
       
      <option value="mll">M</option>
        <option value="mme">Mme</option>
    </select>
  </div>
  </div>
  </div>


  <div class="row">
  <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Adresse</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" name="adresse">
              </div>
            </div>
          </div>
         
         <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Date de naissance</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input class="form-control" type="date" name="date">
            </div>
          </div>
        </div>
       
</div>

    <a class="btn btn-primary" href="{{ route('locataires.index') }}"> Retour</a>
     
      <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
  </div>
</div>


      
      <tbody class="bg-success">
       
        <div >
        </tr>
        </div>
        

      </tbody>
    </table>
    
  </div>
</div>
@endsection

resources/views/locataires/edit.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
 locataire
@endsection


@section('content')
<div class="card mb-4">
  <div class="card-header">
  Creer  nouveau locataire
  </div>
  <div class="card-body">
   @if($errors->any())
    <ul class="alert alert-danger list-unstyled">
      @foreach($errors->all() as $error)
      <li>- {{ $error }}</li>
      @endforeach
    </ul>
    @endif 

    <form method="POST" action="{{ route('locataires.update',$locataire->id) }}" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
      <div class="col">
          <div class="mb-3 row">
            <label for="state" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Type de locataire</label> <br>
            <select class="col-lg-10 col-md-6 col-sm-12"id="type" value="{{ $locataire->type_locataire }}" name="type_locataire">
        <option value="locataire"{{ $locataire->type_locataire == 'locataire' ? 'selected' : '' }}  >locataire
        </option>
        <option value="particulier"{{ $locataire->type_locataire == 'particulier' ? 'selected' : '' }}>Particulier</option>
        <option value="societe"{{ $locataire->type_locataire == 'societe' ? 'selected' : '' }}>Société/Autre</option>
    </select>
  </div>
</div>


        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Nom locataire</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="locataire_name"  value="{{ $locataire->locataire_name }}" type="text" class="form-control">
            </div>
          </div>
        </div>
        
        
        </div>
        <div class="row">
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Prenom locataire</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input name="locataire_prenom"  value="{{ $locataire->locataire_prenom }}" type="text" class="form-control">
              </div>
            </div>
          </div> 
        
        <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">E-mail</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input name="email" value="{{ $locataire->email }}"  type="email" class="form-control">
            </div>
          </div>
        </div>
    
       
    </div>

    <div class="row">
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Ville</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text"  value="{{ $locataire->ville }}" name="ville">
              </div>
           </div>
        </div>
        <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Code postal</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" value="{{ $locataire->code }}"  name="code">
              </div>
           </div>
        </div>

      
         {{-- <div class="col">
          &nbsp;
        </div> --}}
      </div> 
      <div class="row">
    

      <div class="col">
   <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Region</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" value="{{ $locataire->region }}"   name="region">
              </div>
            </div>
         </div>
<div class="col">
          <div class="mb-3 row">
            <label for="civilite" class="col-lg-2 col-md-6 col-sm-12 col-form-label">Civilite
</label> 
<br>
      <select class="col-lg-10 col-md-6 col-sm-12" id="civilite"  value="{{ $locataire->civilite }}"   name="civilite">
        <option value="mll" {{ $locataire->civilite == 'mll'?'selected' : '' }} >M</option>
        <option value="mme" {{ $locataire->civilite == 'mme'?'selected' : '' }} >Mme</option>
    </select>
  </div>
  </div>
  </div>


  <div class="row">
  <div class="col">
            <div class="mb-3 row">
              <label class="col-lg-2 col-md-6 col-sm-12 col-form-label"> Adresse</label>
              <div class="col-lg-10 col-md-6 col-sm-12">
                <input class="form-control" type="text" value="{{ $locataire->adresse }}"   name="adresse">
              </div>
            </div>
          </div>
         
         <div class="col">
          <div class="mb-3 row">
            <label class="col-lg-2 col-md-6 col-sm-12 col-form-label">Date de naissance</label>
            <div class="col-lg-10 col-md-6 col-sm-12">
              <input class="form-control" type="date" value="{{ $locataire->date }}"   name="date">
            </div>
          </div>
        </div>
       
</div>

<a class="btn btn-primary" href="{{ route('locataires.index') }}"> Retour</a>
      <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
  </div>
</div>


      
      <tbody class="bg-success">
       
        <div >
        </tr>
        </div>
        

      </tbody>
    </table>
    
  </div>
</div>
@endsection

resources/views/locataires/index.blade.php
@extends('layouts.master')

@section('title')
Home
@stop

@section('css')

@endsection

@section('title_page1')
Locataires
@endsection


@section('content')
<div class="row">
@if (session()->has('error'))
        <div class="alert alert-danger  bg-danger " id="success-alert">
            <div class="d-flex align-items-center">
               
                <div class="ms-3">
                    <!-- <h6 class="mb-0 text-white">Error</h6> -->
                    <div class="text-white">{{ session()->get('error') }}</div>
                </div>
            </div>
          
        </div>
    @endif 
  
</div>
<div class="dropdown-divider border-black"></div>
<div class="row ml-4 ">
    <div class="col-md-6">
        <h5 class="fw-bold mb-0">liste des locataires</h5>
    </div>

</div>
<div class="dropdown-divider border-black"></div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="button">
                        <a href="{{ route('locataires.create') }}" class="btn btn-sm btn-primary">Creer nouveau locataire</a>
                    </div>
                    <br>
                    <form method="GET">
                        <div class="input-group mb-3">
                            <input type="text" name="search" value="" class="form-control" placeholder="recherche par ville  ..." aria-label="Search" aria-describedby="button-addon2">
                            <button class="btn btn-success" type="submit" id="button-addon2">Recherche</button>
                        </div>
                    </form>

                    <table class="table table-responsive-sm table-bordered table-striped">
                        <thead>
                            <th>Prenom</th>
                            <th>Nom</th>

                            <th>E-mail</th>
                            <th>Ville</th>
                            <th>Type de locataire</th>
                            <th>Action</th>
                        </thead>
                        <tbody>

                            @foreach ($locataires as $locataire)
                            <tr>
                                <td>{{ $locataire->locataire_prenom }}</td>
                                <td>{{ $locataire->locataire_name }}</td>
                                <td>{{ $locataire->email }}</td>
                                <td>{{ $locataire->ville }}</td>
                                <td>{{ $locataire->type_locataire }}</td>
                                <td class="text-center">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a class="btn btn-success" href="{{ route('locataires.edit',$locataire->id) }}">modifier</a>
                                        </div>
                                        <div class="col-md-6">

                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{$locataire->id }}">Supprimer</button>
                                        </div>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="deleteModal{{ $locataire->id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <center>
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h3 class="modal-title">Supprimer la confirmation de locataire</h3><br>
                                                </div>
                                            </center>
                                                <div class="modal-body">
                                                    <p>Êtes-vous sûr de vouloir supprimer cet locataire ?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-hover btn-primary " data-dismiss="modal">Annuler</button>
                                                    <form action="{{route('locataires.destroy',$locataire->id)}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Supprimer</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                
                                </td>

                              

                            </tr>
                            @endforeach





                            </tr>


                        </tbody>
                    </table>

                    @if (isset($message))
    <div class="alert alert-info">{{ $message }}</div>
@endif
                </div>
                <div class="card-body d-flex justify-content-left">
            {!! $locataires->links() !!}
        </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection